# -- Number of replicas
replicas: 1

image:
  # -- geth container image repository
  repository: ethereum/client-go
  # -- geth container image tag
  tag: stable
  # -- geth container pull policy
  pullPolicy: IfNotPresent

# -- Extra args for the geth container
extraArgs: []
  #- --holesky

# -- TOML config file
# @default -- See `values.yaml` for example
config: |
  [Node.P2P]
  DialRatio = 3

jwtSecret:
  name: geth-jwt-secret
  key: jwt-token

extraArgs: 
  - --sepolia

# -- Template used for the default command
# @default -- See `values.yaml`
defaultCommandTemplate: |
  - sh
  - -ac
  - >
    exec geth
    --datadir=/data
    --config=/config/geth.toml
    --http
    --syncmode=snap
    --http.addr=0.0.0.0
    --http.port={{ .Values.httpPort }}
    --http.vhosts=*
    --http.corsdomain=*
    --http.api=eth,net,web3,admin,debug
    --ws
    --ws.addr=0.0.0.0
    --ws.port={{ .Values.wsPort }}
    --ws.origins=*
    --authrpc.jwtsecret=/jwt/jwtsecret
    --authrpc.addr=0.0.0.0
    --authrpc.port={{ .Values.authPort }}
    --authrpc.vhosts=*
    --metrics
    --metrics.addr=0.0.0.0
    --metrics.port={{ .Values.metricsPort }}
    --verbosity=3
  {{- range .Values.extraArgs }}
    {{ tpl . $ }}
  {{- end }}

p2pLoadBalancer:
  # -- Expose P2P port via LoadBalancer
  enabled: true
  # -- Port to be used
  port: 31000

p2pNodePort:
  enabled: true
  tcpNodePort: 30303
  udpNodePort: 30303

ingress:
  # -- Ingress resource for the HTTP API
  enabled: true
  # -- Annotations for Ingress
  annotations: 
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Ingress host
  hosts:
    - host: api.oumla.local
      paths:
        - path: /
          pathType: Prefix
  # -- Ingress TLS
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Affinity configuration for pods
affinity: {}


livenessProbe:
  tcpSocket:
    port: http-rpc
  initialDelaySeconds: 60
  periodSeconds: 120

readinessProbe:
  tcpSocket:
    port: http-rpc
  initialDelaySeconds: 10
  periodSeconds: 10

# -- P2P Port
p2pPort: 30303

# -- HTTP Port
httpPort: 8545

# -- WS Port
wsPort: 8545

# -- Engine Port (Auth Port)
authPort: 8551

# -- Metrics Port
metricsPort: 6060

persistence:
  # -- Uses an EmptyDir when not enabled
  enabled: true
  # -- Use an existing PVC when persistence.enabled
  existingClaim: null
  # -- Access mode for the volume claim template
  accessModes:
  - ReadWriteOnce
  # -- Requested size for volume claim template
  size: 2000Gi
  # -- Use a specific storage class
  # E.g 'local-path' for local storage to achieve best performance
  # Read more (https://github.com/rancher/local-path-provisioner)
  storageClassName: standard
  # -- Annotations for volume claim template
  annotations: {}
  # -- Selector for volume claim template
  selector: {}
  #   matchLabels:
  #     app.kubernetes.io/name: something


rbac:
  # -- Specifies whether RBAC resources are to be created
  create: true
  # -- Required ClusterRole rules
  # @default -- See `values.yaml`
  clusterRules:
     # Required to obtain the nodes external IP
    - apiGroups: [""]
      resources:
      - "nodes"
      verbs:
      - "get"
      - "list"
      - "watch"
  # -- Required ClusterRole rules
  # @default -- See `values.yaml`
  rules:
    # Required to get information about the services nodePort.
    - apiGroups: [""]
      resources:
      - "services"
      verbs:
      - "get"
      - "list"
      - "watch"

# -- The security context for pods
securityContext:
  fsGroup: 10001
  runAsGroup: 10001
  runAsNonRoot: true
  runAsUser: 10001

containerSecurityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


serviceMonitor:
  # -- If true, a ServiceMonitor CRD is created for a prometheus operator
  # https://github.com/coreos/prometheus-operator
  enabled: true
  # -- Path to scrape
  path: /debug/metrics/prometheus
  # -- Alternative namespace for ServiceMonitor
  namespace: null
  # -- Additional ServiceMonitor labels
  labels:
    release: prom
  # -- Additional ServiceMonitor annotations
  annotations: {}
  # -- ServiceMonitor scrape interval
  interval: 1m
  # -- ServiceMonitor scheme
  scheme: http
  # -- ServiceMonitor TLS configuration
  tlsConfig: {}
  # -- ServiceMonitor scrape timeout
  scrapeTimeout: 30s
  # -- ServiceMonitor relabelings
  relabelings: []
