project_id         = "your-gcp-project-id"
region            = "us-central1"
zone              = "us-central1-a"
cluster_name      = "geth-mainnet-cluster"
backup_bucket_name = "geth-backups-your-project"