{{- if .Values.p2pNodePort.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geth.fullname" $ }}-p2p-nodeport-0
  labels:
    {{- include "geth.labels" $ | nindent 4 }}
    pod: {{ include "geth.fullname" $ }}-0
    type: p2p
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: p2p-tcp
      port: {{ include "geth.p2pPort" $ }}
      protocol: TCP
      targetPort: p2p-tcp
      nodePort: {{ .Values.p2pNodePort.tcpNodePort }}
    - name: p2p-udp
      port: {{ include "geth.p2pPort" $ }}
      protocol: UDP
      targetPort: p2p-udp
      nodePort: {{ .Values.p2pNodePort.udpNodePort }}
  selector:
    {{- include "geth.selectorLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: "{{ include "geth.fullname" $ }}-0"
{{- end }}