name: Helm Lint

on:
  push:
    paths:
      - "charts/**"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
        with:
          version: v3.13.0
      - name: Helm Lint
        run: helm lint charts/geth