name: Terraform Validation

on:
  push:
    paths:
      - "terraform/**.tf"
      - "terraform/**.tfvars"
  pull_request:
    paths:
      - "terraform/**.tf"
      - "terraform/**.tfvars"

jobs:
  terraform:
    name: Terraform Validate & Format Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6 

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate -no-color

