name: Kind Cluster Test

on:
  push:
    paths:
      - "charts/**"
      - "local/kind-config.yaml"
      - ".github/workflows/kind-test.yml"
  pull_request:

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Kubernetes tools
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Set up KinD cluster
        uses: helm/kind-action@v1.9.0
        with:
          config: local/kind-config.yaml
          wait: 120s